#ifndef _MESSEAGE_HPP_
#define _MESSEAGE_HPP_

#include <string>

using namespace std;

struct Messeage
{
    public:
        const string usage = " is not a tag or a qdo command. See 'qdo --help'.\n";
        const string too_few_parameters = "Too few parameters. You can use:\n\n";
        const string check_need_tag = "Tag is needed.\nUse 'qdo [-check] <tag>' to check a tag.\n";
        const string delete_need_tag = "Tag is needed.\nUse 'qdo [-del] <tag>' to delete a tag.\n";
        const string add_need_tag = "Tag and target command is needed.\nUse 'qdo [-add] <tag> <command>' to add a tag.\n";
        const string add_need_target = "Target command is needed.\nUse 'qdo [-add] <tag> <command>' to add a tag.\n";
        const string simple_help = "qdo <tag>\t\t\tExecute a bound operation\nqdo [-list]\t\t\tList all tags\nqdo [-check] <tag>\t\tCheck for a bound operation\nqdo [-add] <tag> <command>\tAdd a tag\nqdo [-del] <tag>\t\tDelete a tag\n\n'qdo --help' to show full help.\n";
        const string full_help = "This is full help.\n";
        const string init_messeage = "# This file is generated by qdo.\n# You can edit it to add some tags.\n# For example:\n#\n#chrome = start \"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe\"\n#\n# This allows you to run Chrome with 'qdo chrome'.\n";
        const string config_not_exist = "'qdo.conf' does not exist, creating file...\n";
        const string create_success = "'qdo.conf' created.\n";
        const string create_failed = "Failed to create file!\n";
} Messeages;

#endif
